name: Build APK from ZIP

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/build-apk.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo dosyalarını al
        uses: actions/checkout@v4

      - name: Java 17 kur
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: ZIP dosyasını aç
        run: unzip PyLearnAndroid.zip

      - name: Çıkan dosyaları listele
        run: ls -R

      - name: gradlew izin ver
        run: chmod +x PyLearnAndroid/gradlew

      - name: Debug APK üret
        run: cd PyLearnAndroid && ./gradlew assembleDebug

      - name: APK yükle
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: PyLearnAndroid/app/build/outputs/apk/debug/*.apk
